### ISSUE TITLE
choosing the right env_spec

### ISSUE THREAD

**Issue by AlbertDeFusco** [anaconda/ae5-vscode#1]
Like many anaconda-project commands list-env-specs returns keys in alphabetical order rather than lexical. Although we generally recommend users specify a single env_spec `start_vscode.sh` may not pickup the same spec that `anaconda-project prepare` does in `startup.sh`

```yaml
name: double
env_specs:
  b:
    packages: [python=3.7]
  a:
    packages: [python=3.8]
```

```
> anaconda-project list-env-specs
Environments for project: /Users/adefusco/Desktop/double

Name  Description
====  ===========
a
b
```
