### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by AlbertDeFusco** [anaconda/ae5-vscode#10]
this is what works for me

1. clone the repo onto the AE5 master node to `/opt/anaconda/vscode`
1. Enter gravity and cd to vscode directory
```
sudo gravity enter
cd /opt/anaconda/vscode
```
3. Determine workspace image name. Save `WORKSPACE` for later when you need to re-build the image.
```
WORKSPACE=$(kubectl get pods | grep ap-workspace- | \
            awk '{print $1;}' | xargs kubectl describe pod | \
            grep ANACONDA_PLATFORM_IMAGES_EDITOR | awk '{print $2;}')
echo $WORKSPACE
```
4. Build the docker image and push
```
sed -i "s@^FROM .*@FROM $WORKSPACE@" Dockerfile
docker build --build-arg WORKSPACE=$WORKSPACE -t $WORKSPACE-vscode .
docker push $WORKSPACE-vscode
```
5. Change the image used by the workspace pod
```
kubectl edit deploy anaconda-enterprise-ap-workspace
```

Search for `ANACONDA_PLATFORM_IMAGES_EDITOR` You should find it on line 272. Edit the value by appending `vscode`. It should appear as below. On exit the workspace pod will restart.

```yaml
      containers:
      - env:
        - name: DB_URL
          value: anaconda-enterprise-postgres:5432
        - name: SERVICE_MIGRATE
          value: spaces_quick_migrate
        - name: SERVICE_LAUNCH
          value: spaces_quick_launch
        - name: ANACONDA_PLATFORM_IMAGES_APP-PROXY
          value: leader.telekube.local:5000/ae-app-proxy:5.4.0-46.g640c57da1
        - name: ANACONDA_PLATFORM_IMAGES_EDITOR
          value: leader.telekube.local:5000/ae-editor:5.4.0-46.g640c57da1-vscode
```
6. In the operations center edit the platform configuration to add the vscode editor to the UI around line 535. It should look like below
```yaml
          workspace:
            tools:
              notebook:
                default: true
                label: Jupyter Notebook
                packages: [notebook]
              jupyterlab:
                label: JupyterLab
                packages: [jupyterlab]
              vscode:
                label: VS Code
                packages: [vscode]
              anaconda-platform-sync:
                label: Anaconda Project Sync
                packages: [anaconda-platform-sync]
```
7. Restart the UI and workspace pods
```
kubectl delete pods -l 'app in (ap-workspace, ap-ui)'
```

If you need to rebuild the image you can do so rapidly with the following script, which must be run from within gravity at the /opt/anaconda/vscode directory. You won't need to edit any yaml files.

```bash
#!/bin/bash

set -e

WORKSPACE=leader.telekube.local:5000/ae-editor:5.4.0-46.g640c57da1 # valid for 5.4.0
docker build --build-arg WORKSPACE=$WORKSPACE -t $WORKSPACE-vscode .
docker push $WORKSPACE-vscode
kubectl delete pod -l app=ap-workspace
```
